
services:
  zabbix:
    image: zabbix/zabbix-server-mysql
    container_name: zabbix
    restart: unless-stopped
    ports:
    - "10051:10051/tcp"
    - "162:162/udp"
    - "10050:10050/tcp"
    depends_on:
      - zabbix-database
    environment:
      - DB_SERVER_HOST=zabbix-database
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root

  zabbix-database:
    image: mysql:8.0
    container_name: zabbix-database
    command: --character-set-server=utf8 --collation-server=utf8_bin
    restart: unless-stopped
    environment:
      - DB_SERVER_HOST=zabbix-database
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306/tcp"
    volumes:
      - ./zabbix-db-data:/var/lib/mysql

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web
    restart: unless-stopped
    ports:
    - "8080:8080/tcp"
    environment:
      - DB_SERVER_HOST=zabbix-database
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root
      - ZBX_SERVER_HOST=zabbix
      - PHP_TZ=UTC
    depends_on:
      - zabbix-database
      - zabbix

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
    - "3000:3000/tcp"

  debian-agent:
    container_name: debian-agent
    build: ./gerenciaveis/debian
    image: gerenciaveis/debian:latest
    ports:
      - "161:161/udp"

  ubuntu-agent:
    container_name: ubuntu-agent
    build: ./gerenciaveis/ubuntu
    image: gerenciaveis/ubuntu:latest
    ports:
      - "1161:161/udp"
